-- Tenant isolation hardening — RLS on tables that were either not protected
-- at all (kb_sop_drafts, assessment_submissions) or that depended on app code
-- to set role correctly (profiles).
--
-- Service-role writes already bypass RLS, so server API routes that use the
-- service-role client (signup/complete, ghost-*, etc.) continue to work
-- unchanged. The policies below only affect direct browser (anon /
-- authenticated) traffic.

-- --------------------------------------------------------------------------
-- helper: is the calling user an admin? Used by every policy below.
-- security definer so it can read profiles even when RLS is on.
-- --------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select role = 'admin' from public.profiles where id = auth.uid()),
    false
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

-- --------------------------------------------------------------------------
-- profiles
--
-- The signup flow now creates profiles server-side with role hardcoded to
-- 'client'. These policies are the defense-in-depth layer so that *any*
-- other code path (now or future) cannot let a user assign themselves
-- role = 'admin' or move themselves into another organization.
-- --------------------------------------------------------------------------
alter table public.profiles enable row level security;

drop policy if exists profiles_self_select on public.profiles;
drop policy if exists profiles_admin_select on public.profiles;
drop policy if exists profiles_self_insert_client on public.profiles;
drop policy if exists profiles_admin_insert on public.profiles;
drop policy if exists profiles_self_update on public.profiles;
drop policy if exists profiles_admin_update on public.profiles;
drop policy if exists profiles_admin_delete on public.profiles;

-- Read: your own row, or admins see all
create policy profiles_self_select
on public.profiles for select
using (auth.uid() = id or public.is_admin());

-- Insert: a user can create their own profile, but only as 'client'
create policy profiles_self_insert_client
on public.profiles for insert
with check (auth.uid() = id and role = 'client');

-- Insert: admins can create any profile
create policy profiles_admin_insert
on public.profiles for insert
with check (public.is_admin());

-- Update: own row only — role / organization_id mutations are blocked by
-- the trigger below so we don't need a complex WITH CHECK clause here
create policy profiles_self_update
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- Update: admins can update anything
create policy profiles_admin_update
on public.profiles for update
using (public.is_admin())
with check (public.is_admin());

-- Delete: admins only
create policy profiles_admin_delete
on public.profiles for delete
using (public.is_admin());

-- Trigger: block self-promotion to admin and lateral tenant moves
create or replace function public.profiles_block_privilege_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_is_admin boolean;
begin
  -- Service-role writes set auth.uid() to NULL — let them through.
  if auth.uid() is null then
    return new;
  end if;

  select role = 'admin' into caller_is_admin
  from public.profiles
  where id = auth.uid();

  if coalesce(caller_is_admin, false) = false then
    if new.role is distinct from old.role then
      raise exception 'Only admins can change profile.role';
    end if;
    if new.organization_id is distinct from old.organization_id then
      raise exception 'Only admins can change profile.organization_id';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists tr_profiles_block_privilege_escalation on public.profiles;
create trigger tr_profiles_block_privilege_escalation
before update on public.profiles
for each row execute function public.profiles_block_privilege_escalation();

-- --------------------------------------------------------------------------
-- kb_sop_drafts
--
-- Internal operator drafts. Admins can do anything; org members can read
-- drafts associated with their own org's tickets (so a future client-facing
-- "KB articles published from your tickets" surface still works).
-- All writes are blocked for non-admins — drafts are generated by the
-- service-role AI routes.
-- --------------------------------------------------------------------------
alter table public.kb_sop_drafts enable row level security;

drop policy if exists kb_sop_drafts_admin_all on public.kb_sop_drafts;
drop policy if exists kb_sop_drafts_org_select on public.kb_sop_drafts;

create policy kb_sop_drafts_admin_all
on public.kb_sop_drafts for all
using (public.is_admin())
with check (public.is_admin());

create policy kb_sop_drafts_org_select
on public.kb_sop_drafts for select
using (
  exists (
    select 1
    from public.tickets t
    join public.profiles p on p.id = auth.uid()
    where t.id = kb_sop_drafts.ticket_id
      and t.organization_id = p.organization_id
  )
);

-- --------------------------------------------------------------------------
-- assessment_submissions
--
-- Public lead-capture form (anonymous insert is allowed); only admins may
-- read or update. The public /api/assessment/submit route uses the service
-- role and bypasses RLS, so the anon insert policy is defense in depth in
-- case the form is ever wired directly to the anon client.
-- --------------------------------------------------------------------------
alter table public.assessment_submissions enable row level security;

drop policy if exists assessment_submissions_public_insert on public.assessment_submissions;
drop policy if exists assessment_submissions_admin_all on public.assessment_submissions;

create policy assessment_submissions_public_insert
on public.assessment_submissions for insert
to anon, authenticated
with check (true);

create policy assessment_submissions_admin_all
on public.assessment_submissions for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
